### ISSUE TITLE
[Feature]: Create a figma template for the filter on the explore page

### ISSUE THREAD

**Issue by nac62116** [mint-vernetzt/community-platform#109]
### What do you like to be improved?

- Filtering for Aktivitätsgebiete (Bundesländer & Bundesweit) / Biete / Suche
- Generic message when no profile was found
- Reset the filter

**Comment by Hejabea** [comment]
Think about colors and/or headlines.

**Comment by nac62116** [comment]
New version with:
- Different filter UI for each category (profiles, organizations, events)
