### ISSUE TITLE
[Bug]: Tests failing if database not configured

### ISSUE THREAD

**Issue by sstenz** [mint-vernetzt/community-platform#15]
### What happened?

A bug happened!

**Comment by C0mput3r5c13nt15t** [comment]
Update:

The tests failing are the ones in the register route, the problem being that they aren't clean unit tests but are actually testing the e2e logic. In detail they are sending requests to superbase and evaluating the response, hence they should be integration tests not unit tests.

The "solution" to the problem would be to comment out all tests except the "call loader" test. This is the same "solution" also found in the login route, where a similar issue seems to have occurred.

**Comment by phollome** [comment]
Will be replaced by #20
