### ISSUE TITLE
[Feature]: Toggle privileged members of organization

### ISSUE THREAD

**Issue by phollome** [mint-vernetzt/community-platform#165]
### What do you like to be improved?

- What happens if I toggle to unprivileged? Forbidden? Show a read-only view?
   - Am I always the last privileged user?
- Can I toggle other people to privileged user without notification?
- What happens if I delete my profile and I'm the last privileged member?

**Comment by nac62116** [comment]
Update:

- Implemented first version of privilege button
- multiple persons can be privileged
- current user cannot toggle himself as unprivileged or remove himself from the team
- There is no notification about privilege changes yet
- You cannot delete your profile when you are a privileged member of an organization
