### ISSUE TITLE
[Feature]: Add youtube and instagram to organization

### ISSUE THREAD

**Issue by phollome** [mint-vernetzt/community-platform#194]
### What do you like to be improved?

Some awesome stuff!

**Comment by nac62116** [comment]
- [ ] Add youtube and Instagram to schema
- [ ] Add them to the edit routes
- [ ] Add their icons

**Comment by nac62116** [comment]
- Get icons from bootstrap or fontawesome (ask sirko)

**Comment by nac62116** [comment]
@sstenz 
- [ ] Check if the correct icons are used (currently from bootstrap, [YouTube](https://icons.getbootstrap.com/icons/youtube/), [Instagram](https://icons.getbootstrap.com/icons/instagram/)
- [ ] Beautify the icon representation on show organization and profile route
