### ISSUE TITLE
[Feature]: Footer mit Impressum + Datenschutzerklärung

### ISSUE THREAD

**Issue by ingalef** [mint-vernetzt/community-platform#236]
### What do you like to be improved?

Some awesome stuff! :)

Gibt es schon ein Ticket für den Footer auf der live-Plattform, mit Link zur Unterseite Impressum und Unterseite Datenschutzerklärung? Beim Klicken auf DS-Erklärung wird ja auf die Seite von mint-vernetzt verlinkt, wie auch in der Ansicht beim Registrieren. 

Hier ist der Text für das Impressum von morgenstern: 

MINTvernetzt ist ein Verbundprojekt des / der: 

• Körber-Stiftung 

• matrix gGmbH 

• Stifterverbands für die deutsche Wissenschaft e.V. 

• Nationalen MINT 

• Forum e.V. 

• Universität Regensburg 

Als Dienstanbieterin im Sinne des § 5 TMG, Kontaktstelle, Betreiberin und Vertragspartnerin nach diesen Bestimmungen ist die matrix 

Gesellschaft für Beratung in Wirtschaft, 

Politik und Verwaltung mbH & Co. KG 

Schloss Elbroich 

Am Falder 4 

40589 Düsseldorf 

  

Vertretungsberechtigt: 

Gregor Frankenstein-von der Beeck 

Guido Lohnherr 

  

Tel.: +49(0)211-75707-910 

Fax: +49(0)211-987300 

E-Mail: [info@matrix-gmbh.de](mailto:info@matrix-gmbh.de) 

  

Umsatzsteueridentifikationsnummer: (USt. Ident-Nr) DE 222703085 

Amtsgericht Düsseldorf – HRA 15120 

  

berufen. Inhaltlich verantwortlich nach § 18 MStVist Arne Klauke, erreichbar über die Dienstanbietern.

**Comment by nac62116** [comment]
Closed by pull request #250
