### ISSUE TITLE
[Feature]: Move image upload into a modal

### ISSUE THREAD

**Issue by nac62116** [mint-vernetzt/community-platform#281]
### What do you like to be improved?

Some awesome stuff!

**Comment by phollome** [comment]
Figma: https://www.figma.com/file/EcsrhGDlDkVEYRAI1qmcD6/MINTvernetzt?node-id=283%3A2170

**Comment by manuelportela** [comment]
- own route for upload handling and deletion
- feature: delete current image (-> fall back initials)
- get handling out of profile index
- crop? (see: https://www.npmjs.com/package/react-image-crop or alternative)
