### ISSUE TITLE
Calendar file download

### ISSUE THREAD

**Issue by phollome** [mint-vernetzt/community-platform#294]
`*.ics`

[ics](https://www.npmjs.com/package/ics)

ics created on update #285

**Comment by nac62116** [comment]
Is it still the plan to create the ics on event settings update?

- ics is not in the prisma schema
- It could also be created on download? (Easier and less code. Are there Arguments against it?)

**Comment by nac62116** [comment]
To download the ics:

Maybe there is a remix download package

**Comment by nac62116** [comment]
@phollome 

Had to define ics as optional string inside the prisma schema. if it where required we would need to add it to existing events table entries on stage and prod.

Maybe we can change it to required when the event feature is released?

**Comment by nac62116** [comment]
Update on wip commit:
- Continue to work on this issue depends on how we decide to manage the ics
- see #438 and #435
