### ISSUE TITLE
[Bug]: CSRF does not work on create event route

### ISSUE THREAD

**Issue by phollome** [mint-vernetzt/community-platform#320]
### What happened?

 I was not able to get this running. Multiple tokens are created. Session holds the first the form the last.
 See branch [csrf-does-not-work-on-create-event](https://github.com/mint-vernetzt/community-platform/tree/csrf-does-not-work-on-create-event)

**Comment by nac62116** [comment]
CSRF is currently removed from all routes and needs a fresh start.

So this ticket is closed.
