### ISSUE TITLE
[Bug]: User count on username creation

### ISSUE THREAD

**Issue by phollome** [mint-vernetzt/community-platform#326]
### What happened?

If users with same name register the count of same names is added to the username. If a user deletes its profile with a username below user count new users with same name can't register because username is already taken.

Example:
- usernames = janedoe, janedoe1, janedoe2 --> count 3
- janedoe1 deletes its profile --> count 2
- Jane Doe wants to register --> username janedoe2 is already taken

**Comment by nac62116** [comment]
Closed as we now generate a slug from the current timestamp to ensure uniqueness.

Closed by #729
