### ISSUE TITLE
[Bug]: Limit document upload size to 5 MB

### ISSUE THREAD

**Issue by nac62116** [mint-vernetzt/community-platform#477]
Currently large document upload is not working (no error thrown and no upload done).

**Comment by nac62116** [comment]
[Vorstellung Konzept MINT-DataLab am 02.03.22.pdf](https://github.com/mint-vernetzt/community-platform/files/9968962/Vorstellung.Konzept.MINT-DataLab.am.02.03.22.pdf)

**Comment by nac62116** [comment]
[Mittelgroßes Testdokument.pdf](https://github.com/mint-vernetzt/community-platform/files/9968973/Mittelgrosses.Testdokument.pdf)

**Comment by manuelportela** [comment]
http://192.168.169.97:3000/event/diemintwoche-l95trsmg/settings/documents
