### ISSUE TITLE
[Feature]: Styling event detail page

### ISSUE THREAD

**Issue by sstenz** [mint-vernetzt/community-platform#488]
### What do you like to be improved?

The styling

**Comment by sstenz** [comment]
I will need some more data from the child events in the detail view.  How do we want to handle this? I'll make a list here for now:

- date output:
Single: 30. August 2022 | 10:00 Uhr or 
Duration: 30. Aug. – 10. Sept. 2022 | 10:00 Uhr

**Comment by sstenz** [comment]
- location: How can I tell which status to output?
If there is a conferenceLink but no venueName = online
If there is a venueName but no conferenceLink = offline
If there is both = hybrid?

**Comment by sstenz** [comment]
- is there a limit on the WaitingList
- Can we count the users on WaitingList?

**Comment by sstenz** [comment]
- isParticipant doesnt work
- Do we need a cancelled status in the list view or do we not show cancelled events?

**Comment by sstenz** [comment]
Team avatar is  missing

**Comment by phollome** [comment]
> * location: How can I tell which status to output?
>   If there is a conferenceLink but no venueName = online
>   If there is a venueName but no conferenceLink = offline
>   If there is both = hybrid?

We've added a new field called `stage`.
