### ISSUE TITLE
[Feature]: Applying the award banner to project detail page

### ISSUE THREAD

**Issue by nac62116** [mint-vernetzt/community-platform#638]
When Bea finished designing the award banner, please add it to the project detail page.

**Comment by sstenz** [comment]
@nac62116 

I think we need more data for the awards:

- Shorttitle for the banner
- Year of the award (subline is needed elsewhere and can' t be used for this).

**Comment by nac62116** [comment]
Good point Sirko! Lets talk about that in the daily.
