### ISSUE TITLE
[Feature]: Initial content

### ISSUE THREAD

**Issue by phollome** [mint-vernetzt/community-platform#698]
- define edge cases
- create initial content
- script it (add to Makefile)

**Comment by nac62116** [comment]
Add environment check to script:
- Check inside .env if database environment is localhost else throw
- Add flag -f (--force) to bypass this rule

Define Cases:

Profiles:
- Standard Profile
- Smallest Profile
- Largest Profile
- Random field sizes Profile
- Profiles with single fields missing
- Profiles with only one field
- Edge Case: Unicode Profile

Organizations:
- TODO

Events:
- TODO

Relations:
- TODO

**Comment by nac62116** [comment]
https://www.npmjs.com/package/faker
https://ngneat.github.io/falso/
