### ISSUE TITLE
[Feature]: update TypeScript

### ISSUE THREAD

**Issue by phollome** [mint-vernetzt/community-platform#725]
- [Release Notes](https://github.com/microsoft/TypeScript/releases)
- [Breaking Changes](https://github.com/microsoft/TypeScript/wiki/Breaking-Changes)
- [API Breaking Changes](https://github.com/microsoft/TypeScript/wiki/API-Breaking-Changes)
- Could not find upgrade guides or codemods

**Comment by nac62116** [comment]
Closed: Resolved during the update process (see #704)
