### ISSUE TITLE
[Feature]: Implement Matomo

### ISSUE THREAD

**Issue by phollome** [mint-vernetzt/community-platform#96]
### What do you like to be improved?

self-hosted Matomo

- see [https://github.com/remix-run/remix/blob/main/examples/google-analytics/app/root.tsx](https://github.com/remix-run/remix/blob/main/examples/google-analytics/app/root.tsx)

estimate 4h

**Comment by manuelportela** [comment]
# Tasks accomplished
- analysed problem and possible solutions
- added to root.tsx
- added script
- added lifecycle tracking
- added specifics to .env
- testing

# TODO
- embed matomo opt-out into privacy policy
- install cutstom opt out plugin
- add font to matomo
- @phollome: we need to add matomo specific .env for CD 

# Help needed
- @nac62116 I need access as superuser to matomo to install plugin
