### ISSUE TITLE
[Bug]: error in profile data when area data is missing

### ISSUE THREAD

**Issue by manuelportela** [mint-vernetzt/community-platform#97]
### What happened?

I forgot to ingest the area data and by visiting my profile page I received an error:
see createAreaOptionFromData.ts:16:26

I expect that the error should be handled even if the app cannot work without area data

**Comment by nac62116** [comment]
If this is still an Issue it also affects:
- [ ] ...the areas of organizations
- [ ] ...the areas of events

**Comment by nac62116** [comment]
@phollome 
Is this still an issue?

**Comment by nac62116** [comment]
Handle missing ingest

**Comment by nac62116** [comment]
Missing ingest is now handled by the check-diffs script and requests the user to ingest the data via the make commands
